tiys/tiys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from pages.sitemaps import PagesSitemap
from channel.sitemaps import ChannelProfileSitemap
from youtuber.sitemaps import YoutuberProfileSitemap
from top_five.sitemaps import TopFiveSitemap


sitemaps = {
    'pages': PagesSitemap,
    'channel': ChannelProfileSitemap,
    'youtuber': YoutuberProfileSitemap,
    'top_five': TopFiveSitemap,
}

urlpatterns = [
    path('', include('pages.urls')),
    path('youtuber/', include('youtuber.urls')),
    path('channel/', include('channel.urls')),
    path('top-5/', include('top_five.urls')),
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

tiys/pages/models.py
from django.db import models
from django.utils.timezone import now


class Submit(models.Model):
    channel_name = models.CharField(max_length=150, unique=True)
    youtube_url = models.URLField(max_length=200, unique=True)
    date = models.DateField(default=now,)

    def __str__(self):
        return self.channel_name


class Faq(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField(max_length=300)
    date = models.DateField(default=now, )

    def __str__(self):
        return self.title

tiys/pages/templates/pages/about.html
{% extends "pages/base.html" %}
{% block title %} About Us {% endblock %}
{% block css %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'pages/css/about-page.css' %}">


{% endblock %}

{% block content %}
<div class="main">
    <!--breadcrumbs-->
    <ul class="breadcrumb">
        <li><a href="{% url 'homepage' %}">Home</a></li>
        <li>About Us</li>
    </ul>
<!--end breadcrumbs-->
<!--about Page title-->
    <div class="about-title">
        <h1>About Us</h1>
    </div>
<!--End about page title-->
<!--about page content-->
    <div class="about-content">
        <p>Youtube has been there for quite a long time in India, but gained more interest after the internet boom in recent couple of years, this created a large audience base of YouTube in India.
            This also created an opportunity for some people among the audience to showcase their knowledge, creativity and talent with others and thus making them a content creator.
            Through recent years many creators have established themselves on YouTube by providing amazing content.
            The number of content creators and channels is very large in number and it is hard to know each and every indian content creator or channel.
            The main goal of this website is to collect and provide information and details about all the content creators of YouTube India in one place and proudly recognize all of them as "The Indian Youtubers" aka TIYS! </p>
        <p>On  tiys.in website you will find web pages containing details of indian youtubers and channels. Since there are numerous indian youtubers and channels, Hence In order to diversify creator or channel specifically, all the channels webpages are specified in two categories
        </p>
        <ol>
            <li>Based on channel category</li>
            <li>Based on the subscriber count category</li>
        </ol>
        <p>The channel categories we are as follows-</p>
            <ol>
                {% for category in category_list %}
                <li>{{category.name}}</li>
            {% endfor %}
            </ol>

        <p>The subscriber count categories we are as follows-</p>
            <ul>
                {% for subs in subscriber_list %}
                <li>{{subs.name}}</li>
            {% endfor %}
            </ul>
        <p>Every youtuber or channel will have a separate webpage on their channel name containing following details-
        </p>
        <ol>
            <li>Channel name</li>
            <li>Channel owner name</li>
            <li>Individual channel owner picture</li>
            <li>Subscriber count</li>
            <li>Total views</li>
            <li>Total videos</li>
            <li>Date of joining youtube</li>
            <li>1st video upload date</li>
            <li>Link to your Youtube Channel </li>
            <li>Link to your Instagram account</li>
            <li>Link to your Twitter page</li>
            <li>Link to your Facebook page</li>
            <li>Link to your Website/Blog</li>
        </ol>
        <p>Details like subscriber count, total views, total videos will be updated on a regular basis.</p>
        <p>Every creator is valuable for their amazing contribution to the community, so on this website  you will find detailed and dedicated webpage of  every indian youtuber or channels having subscriber count 10k and below, all the way up to 10M subscribers and above.</p>
        <p>Diversifying creators and channels on the basis of channel category and subscribers count allows more than fifty groups. This number is quite large, so we thought maybe we can analyze details and provide the audience with detail, who are the top creators or channels of  a particular category. This top list of creators and channels will be published regularly on our website Top 5 page. These Top 5 lists will also be published on our youtube channel in a fun and amazing way.</p>
        <p>These are a few initial steps from us to bring together all the indian youtubers and channels and recognize them for their valuable content.</p>
        <p>So if you are a indian youtuber or own a channel join now and become a part of the TIYS community</p>
    </div>

    <div class="submit">
        <h1>Are you an Indian Youtubers or owns a Channel.??</h1>
        <h5>Submit your details now and get a webpage on our website</h5>
        <a href="{% url 'submit-page' %}">Submit Now</a>
    </div>
</div>
{% endblock %}

tiys/pages/templates/pages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TIYS | {% block title %}{% endblock %}  </title>
    {% block meta %}{% endblock %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'pages/css/main.css' %}">
    {% block css %}

    {% endblock %}

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Alfa+Slab+One&family=Goldman:wght@400;700&family=Monoton&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/de12b7a1e9.js"></script>
    {% block script %}

    {% endblock %}


</head>
<body>
<div class="container">
    {% include 'navbar.html' %}
    {% block content %} {% endblock %}
    {% include 'footer.html' %}
</div>
{% block bodyscript %} {% endblock %}
</body>
</html>

tiys/pages/templates/pages/contact.html
{% extends "pages/base.html" %}
{% block title %} Contact Us {% endblock %}
{% block css %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'pages/css/contact-page.css' %}">


{% endblock %}

{% block content %}
<div class="main">
<!--breadcrumbs-->
    <ul class="breadcrumb">
        <li><a href="{% url 'homepage' %}">Home</a></li>
        <li>Contact Us</li>
    </ul>
<!--end breadcrumbs-->
<div class="contact">
    <div class="contact-left">
    <h1>Contact Us</h1>
    <h3>Communication is the best way to transfer information .
        It also helps to improve the accuracy of information’s data which is a must for creating best quality content.</h3>
    <h3>For any suggestions, feedback and any other queries:- </h3>
    <h4>e-mail : info@tiys.in</h4>
    <h5>You can also contact via our social media. links below!</h5>
    </div>
    <div class="contact-right">
    <img src="{% static 'pages/images/contact.png' %}" alt="" >
    </div>
</div>
    <div class="submit">
        <h1>Are you an Indian Youtubers or owns a Channel.??</h1>
        <h5>Submit your details now and get a webpage on our website</h5>
        <a href="{% url 'submit-page' %}">Submit Now</a>
    </div>
</div>
{% endblock %}

tiys/pages/templates/pages/faq.html
{% extends "pages/base.html" %}
{% block title %} F.A.Q {% endblock %}
{% block css %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'pages/css/faq-page.css' %}">

{% endblock %}

{% block content %}
<div class="main">
    <div class="faq">
        {% for faq in faq_list %}

        <button class="faq-title">
            {{faq.title}}
        </button>
        <div class="faq-description">
            {{faq.description}}
        </div>
        {% endfor %}


  </div>

</div>


{% endblock %}

{% block bodyscript %}
<script>
var acc = document.getElementsByClassName("faq-title");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.display === "block") {
      panel.style.display = "none";
    } else {
      panel.style.display = "block";
    }
  });
}
</script>
{% endblock %}

tiys/pages/templates/pages/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TIYS | The Indian Youtubers </title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'pages/css/main.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'pages/css/home-page.css' %}">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Alfa+Slab+One&family=Goldman:wght@400;700&family=Monoton&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/de12b7a1e9.js"></script>


</head>
<body>
<div class="container">
    <div class="header">
        {% include 'navbar.html' %}
        <div class="header-hero">
             <div class="header-hero-left">
                <img src="{% static 'pages/images/home-hero.png' %}" alt="" >
             </div>
             <div class="header-hero-right">
                <h1>Welcome to TIYS</h1>
                 <h3>The places to find all The Indian Youtubers</h3>
             </div>
        </div>
    </div>

    <div class="about">
        <div class="about-left">
            <img src="{% static 'pages/images/home-about.png' %}" alt="" >
        </div>
        <div class="about-right">
            <h1>About us</h1>
            <p>Youtube has been there for quite a long time in India, but gained more interest after the internet boom in recent couple of years, this created a large audience base of YouTube in India.
            This also created an opportunity for some people among the audience to showcase their knowledge, creativity and talent with others and thus making them a content creator.
            Through recent years many creators have established themselves on YouTube by providing amazing content.</p>

            <a href="{% url 'about-page' %}">Know More....</a>
        </div>
    </div>

    <div class="count">
        <div class="count-item">
            <div class="count-item-number">{{ channel_category_count }}</div>
            <div class="count-item-title">Channel Category</div>
        </div>
        <div class="count-item">
            <div class="count-item-number">{{ subscriber_category_count }}</div>
            <div class="count-item-title">Subscriber Category</div>
        </div>
        <div class="count-item">
            <div class="count-item-number">{{ youtuber_count }}</div>
            <div class="count-item-title">Youtuber Profile</div>
        </div>
        <div class="count-item">
            <div class="count-item-number">{{ channel_count }}</div>
            <div class="count-item-title">Channel Profile</div>
        </div>
    </div>

    <div class="profile">
        <div class="profile-title">
            <h1>PROFILE PAGES</h1>
        </div>
        <div class="profile_type">
            <div class="profile_type_yt">
                <a href="{% url 'youtuber-index' %}">Youtuber's</a>
            </div>
            <div class="profile_type_ch">
                <a href="{% url 'channel-index' %}">Channel's</a>
            </div>
        </div>
    </div>

    <div class="top">
        <div class="top-left">
            <div class="top-left-a">TOP</div>
            <div class="top-left-b">5</div>
        </div>
        <div class="top-right">
            <h1>Youtubers</h1>
            <a href="{% url 'top-five-index' %}">Checkout!</a>
        </div>
    </div>

    <div class="submit">
        <h1>Are you an Indian Youtubers or owns a Channel.??</h1>
        <h5>Submit your details now and get a webpage on our website</h5>
        <a href="{% url 'submit-page' %}">Submit Now</a>
    </div>

    {% include 'footer.html' %}
</div>
</body>
</html>

tiys/pages/templates/pages/privacy.html
{% extends "pages/base.html" %}
{% block title %} Privacy Policy {% endblock %}
{% block css %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'pages/css/privacy-page.css' %}">


{% endblock %}

{% block content %}
<div class="main">
<!--breadcrumbs-->
    <ul class="breadcrumb">
        <li><a href="{% url 'homepage' %}">Home</a></li>
        <li>Privacy Policy</li>
    </ul>
<!--end breadcrumbs-->
<!--privacy Page title-->
    <div class="privacy-title">
        <h1>Privacy Policy</h1>
    </div>
<!--End privacy page title-->
<!--privacy page content-->
    <div class="privacy-content">
	<p>Effective date: November 27, 2019</p>
	<p>Myam Media ("us", "we", or "our") operates the <a href="{% url 'homepage' %}">tiys.in</a> website (hereinafter referred to as the "Service").</p>
	<p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. </p>
    <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our <a href="{% url 'terms-page' %}">Terms and Conditions</a></p>
	<h2>Information Collection And Use</h2>
    <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
    <h3>Types of Data Collected</h3>
    <h4>Personal Data</h4>
    <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>
	<ul>
	<li>Email address</li>
	<li>First name and last name</li>
	<li>Cookies and Usage Data</li>
	</ul>
	<h4>Usage Data</h4>
	<p>We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
	<h4>Tracking &amp; Cookies Data</h4>
	<p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
	<p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
 	<p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
	<p>Examples of Cookies we use:</p>
	<ul>
	<li><b>Session Cookies.</b> We use Session Cookies to operate our Service.</li>
	<li><b>Preference Cookies.</b> We use Preference Cookies to remember your preferences and various settings.</li>
	<li><b>Security Cookies.</b> We use Security Cookies for security purposes.</li>
	</ul>
	<h3>Use of Data</h3>
	<p>Myam Media uses the collected data for various purposes:</p>
	<ul>
	<li>To provide and maintain the Service</li>
	<li>To notify you about changes to our Service</li>
	<li>To allow you to participate in interactive features of our Service when you choose to do so</li>
	<li>To create blog post regarding the Service</li>
	<li>To provide customer care and support</li>
	<li>To provide analysis or valuable information so that we can improve the Service</li>
	<li>To monitor the usage of the Service</li>
	<li>To detect, prevent and address technical issues</li>
	</ul>
	<h3>Transfer Of Data</h3>
	<p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
	<p>If you are located outside India and choose to provide information to us, please note that we transfer the data, including Personal Data, to India and process it here.</p>
	<p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
	<p>Myam Media will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
	<h3>Source of Data</h3>
	<p>All the data provided on the channel webpages are gathered from the channels owns about page description area i.e channel owner name, social media links, date of joining, subscriber count &amp; total views. Most of this information is collected manually. So in order to gather information missed by us, we provided a submit page where channel owners can submit information or make any changes in the existing information  </p>
	<h3>Disclosure Of Data</h3>
	<h4>Legal Requirements</h4>
	<p>Myam Media may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
	<ul>
	<li>To comply with a legal obligation</li>
	<li>To protect and defend the rights or property of TIYS &amp;amp; Myam Media</li>
	<li>To prevent or investigate possible wrongdoing in connection with the Service</li>
	<li>To protect the personal safety of users of the Service or the public</li>
	<li>To protect against legal liability</li>
	</ul>
	<h3>Security Of Data</h3>
	<p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
	<h3>Service Providers</h3>
	<p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used or to show ads.</p>
	<p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
	<h2>Analytics</h2>
	<p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
	<h3>Google Analytics</h3>
	<p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
	<p>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.
	For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page: <a href="https://policies.google.com/privacy">https://policies.google.com/privacy</a></p>
	<h3>Google Adsense</h3>
	<h4>Google advertising cookies</h4>
	<p>Google uses cookies to help serve the ads it displays on the websites of its partners, such as websites displaying Google ads or participating in Google certified ad networks. When users visit a Google partner's website, a cookie may be dropped on that end user's browser.</p>
	<ul>
	<li>Third party vendors, including Google, use cookies to serve ads based on a user's prior visits to your website or other websites.</li>
	<li>Google's use of advertising cookies enables it and its partners to serve ads to your users based on their visit to your sites and/or other sites on the Internet.</li>
	<li>Users may opt out of personalized advertising by visiting <a href="https://www.google.com/settings/ads">Ads Settings.</a> (Alternatively, you can direct users to opt out of a third-party vendor's use of cookies for personalized advertising by visiting <a href="www.aboutads.info.">www.aboutads.info.</a> )</li>
		</ul>
	<p>If you have <a href="https://support.google.com/dfp_premium/answer/94152">not opted out of third-party ad serving</a>, the cookies of other <a href="https://support.google.com/dfp_premium/answer/94149">third-party vendors or ad networks</a> may also be used to serve ads on your site, which should also be disclosed in your privacy policy in the following manner:</p>
	<ul>
	<li>Notify your site visitors of the third-party vendors and ad networks serving ads on your site.</li>
	<li>Provide links to the appropriate vendor and ad network websites.</li>
	<li>Inform your users that they may visit those websites to opt out of the use of cookies for personalized advertising (if the vendor or ad network offers this capability). Alternatively, you can direct users to opt out of some third-party vendors’ uses of cookies for personalized advertising by visiting <a href="www.aboutads.info">www.aboutads.info</a>.</li>
	</ul>
	<p>Because publisher sites and laws across countries vary, we're unable to suggest specific privacy policy language. However, you may wish to review resources such as the <a href="http://www.networkadvertising.org/">Network Advertising Initiative</a> for guidance on drafting a privacy policy. For additional details regarding cookie consent notices, please refer to <a href="http://cookiechoices.org/">cookiechoices.org</a></p>

	<h2>Links To Other Sites</h2>
	<p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
	<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
	<h2>Children's Privacy</h2>
	<p>Our Service does not address anyone under the age of 18 ("Children").</p>
	<p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>
	<h2>Changes To This Privacy Policy</h2>
	<p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
	<p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
	<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
	<h2>Contact Us</h2>
	<p>If you have any questions about this Privacy Policy, please contact us by clicking <a href="{% url 'contact-page' %}">Here</a></p>
    </div>
<!--end privacy page content-->
</div>
{% endblock %}

tiys/pages/templates/pages/submit.html
{% extends "pages/base.html" %}
{% block title %} Submit Details {% endblock %}
{% block css %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'pages/css/submit-page.css' %}">


{% endblock %}
{% block content %}
<div class="main">
<!--breadcrumbs-->
    <ul class="breadcrumb">
        <li><a href="{% url 'homepage' %}">Home</a></li>
        <li>Submit Details</li>
    </ul>
<!--end breadcrumbs-->
<!--Submit Page title-->
<div class="submit-page-title">
    <h1>Submit your Channel Details</h1>
</div>
<!--End Page Submit title-->
<!--Submit Page Description-->
<div class="submit-page-description">
        <h3>Things to keeps in mind before Submitting the Details</h3>
    <ul>
        <li>For better user experience on the webpage, make sure following details are present on the channel description page.
            <ul>
                <li>Channel Owner Name</li>
                <li>Channel Owner Image</li>
                <li>Instagram page link</li>
                <li>Twitter page link</li>
                <li>Facebook page link</li>
                <li>Website/Blog link</li>
            </ul>
        </li>
        <li>Above details will added to the channel webpage after verification.</li>
    </ul>
    <h6>To Know More information check <a href="{% url 'terms-page' %}">Terms and Conditions</a>, <a href="{% url 'faq-page' %}">FAQ</a>, <a href="{% url 'privacy-page' %}">Privacy Policy</a></h6>

</div>
    <hr>
<!--End Submit Page Description-->
<!--submit form-->
<div class="submit-form-container">
    <form action="" method="post" class="submit-form">
        {% csrf_token %}
        <label for="id_channel_name">Channel Name:</label>
        <input type="text" id="id_channel_name" name="channel_name" placeholder="Enter your channel name..">

        <label for="id_channel_name">Youtube URL:</label>
        <input type="text" id="id_youtube_url" name="youtube_url" placeholder="Paste your channel url..">

        <input type="submit" value="Submit">
  </form>
</div>
<!--end submit form-->
</div>

{% endblock %}